services:
  - type: web
    name: stockflow-backend
    env: node
    rootDir: server

    buildCommand: npm ci
    startCommand: npm start

    envVars:
      - key: PORT
        value: 10000

      - key: JWT_SECRET
        generateValue: true

      - key: CLIENT_ORIGIN
        value: https://foursewd-coursework-front.onrender.com

      - key: DB_STORAGE
        value: ./storage/inventory.sqlite
